services:
    php_8:
        container_name: '${APP_NAME_INTERNAL}_php_8'
        image: 'wexample/php-8.2:latest'
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=${DOMAIN_MAIN}
            - VIRTUAL_PORT=80
        volumes:
            # Site folder
            - ${APP_PATH_ROOT}:/var/www/html
            # Security ! Hide and .wex data containing passwords and databases !
            - /var/www/html/.wex
            # Apache
            - ${CONF_WEB_APACHE_CONF}:/etc/apache2/sites-available/000-default.conf
            # Php
            - ${CONF_WEB_PHP_INI}:/etc/php/8.2/fpm/conf.d/99-wex.ini
            - ${CONF_WEB_PHP_INI}:/etc/php/8.2/cli/conf.d/99-wex.ini
            # Mysql dumps
            - ${APP_PATH_WEX}mysql/dumps:/var/www/mysql/dumps
            # Use common certificates storage
            - ${WEX_DIR_PROXY}proxy/certs:/certs
            # Cron management
            - ${APP_PATH_WEX}cron/${APP_ENV}:/var/default.cron
        extends:
            file: ${WEX_COMPOSE_YML_DEFAULT}
            service: default
