services:
    wordpress:
        container_name: '${APP_NAME_INTERNAL}_wordpress'
        image: wordpress:6.1.1-php8.2-apache
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=${DOMAIN_MAIN}
            - VIRTUAL_PORT=80
            # Database
            - WORDPRESS_DB_HOST=${MYSQL_DB_HOST}
            - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
            - WORDPRESS_DB_USER=${MYSQL_DB_USER}
            - WORDPRESS_DB_PASSWORD=${MYSQL_DB_PASSWORD}
            - WORDPRESS_TABLE_PREFIX=${WP_DB_TABLE_PREFIX}
            #- WORDPRESS_DEBUG=1
            #- WORDPRESS_CONFIG_EXTRA=
        volumes:
            # Wordpress
            - ${APP_PATH_ROOT}:/var/www/html
            # Security ! Hide and .wex data containing passwords and databases !
            - /var/www/html/.wex
        extends:
            file: ${WEX_COMPOSE_YML_DEFAULT}
            service: default

    # From : https://stackoverflow.com/a/51001043
    cli:
        container_name: '${APP_NAME_INTERNAL}_cli'
        image: wordpress:cli-2.7.1-php8.2
        environment:
            # Database
            - WORDPRESS_DB_HOST=${MYSQL_DB_HOST}
            - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
            - WORDPRESS_DB_USER=${MYSQL_DB_USER}
            - WORDPRESS_DB_PASSWORD=${MYSQL_DB_PASSWORD}
            - WORDPRESS_TABLE_PREFIX=${WP_DB_TABLE_PREFIX}
        volumes:
            # Wordpress
            - ${APP_PATH_ROOT}:/var/www/html
            # Security ! Hide and .wex data containing passwords and databases !
            - /var/www/html/.wex
            - ${APP_PATH_WEX}wp-cli/:/.wp-cli/
        extends:
            file: ${WEX_COMPOSE_YML_DEFAULT}
            service: default
