services:
    phpmyadmin:
        extends:
            file: ${SERVICE_PHPMYADMIN_YML_BASE}
            service: phpmyadmin
        # Avoid to type login / password on local
        environment:
            - VIRTUAL_HOST=pma.${DOMAIN_MAIN}
            - LETSENCRYPT_HOST=pma.${DOMAIN_MAIN}
            - LETSENCRYPT_EMAIL=${CONTEXT_EMAIL}