version: '2'

services:
    phpmyadmin:
        extends:
            file: ${WEX_COMPOSE_YML_PHPMYADMIN_BASE}
            service: phpmyadmin
        # Avoid to type login / password on local
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_DB_PASSWORD}