services:
    phpmyadmin:
        extends:
            file: ${SERVICE_PHPMYADMIN_YML_BASE}
            service: phpmyadmin
        # Avoid to type login / password on local
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_DB_PASSWORD}