services:
    phpmyadmin:
        container_name: '${CONTEXT_NAME}_phpmyadmin'
        image: phpmyadmin/phpmyadmin:5.2
        environment:
          - LETSENCRYPT_EMAIL=${EMAIL}
          - LETSENCRYPT_HOST=${DOMAIN_PMA}
          - PMA_HOST=${APP_NAME_INTERNAL}_${DB_CONTAINER}
          - PMA_PORT=${MYSQL_DB_PORT}
          - VIRTUAL_HOST=${DOMAIN_PMA}
        extends:
            file: ${SERVICE_DEFAULT_YML_ENV}
            service: default
        profiles:
          - env_dev
          - env_local