version: '3'

services:
    phpmyadmin:
        container_name: '${APP_NAME_INTERNAL}_phpmyadmin'
        image: phpmyadmin/phpmyadmin:4.9
        environment:
          - LETSENCRYPT_EMAIL=${EMAIL}
          - LETSENCRYPT_HOST=${DOMAIN_PMA}
          - PMA_HOST=${APP_NAME_INTERNAL}_${DB_CONTAINER}
          - VIRTUAL_HOST=${DOMAIN_PMA}
        restart: always
        networks:
          - wex_net