version: '2'

services:
    phpmyadmin:
        container_name: '${APP_NAME_INTERNAL}_phpmyadmin'
        image: phpmyadmin/phpmyadmin:4.9
        environment:
          - LETSENCRYPT_EMAIL=${EMAIL}
          - LETSENCRYPT_HOST=${DOMAIN_PMA}
          - PMA_HOST=${APP_NAME_INTERNAL}_${DB_CONTAINER}
          - VIRTUAL_HOST=${DOMAIN_PMA}
        restart: always
        networks:
          - tmp_wex_net
        volumes:
            - ${CONF_PHPMYADMIN_PHP_INI}:/etc/php/7.1/apache2/conf.d/99-wex.ini
            - ${CONF_PHPMYADMIN_PHP_INI}:/etc/php/7.2/apache2/conf.d/99-wex.ini
            - ${CONF_PHPMYADMIN_PHP_INI}:/etc/php/7.3/apache2/conf.d/99-wex.ini
            - ${CONF_PHPMYADMIN_PHP_INI}:/etc/php/7.4/apache2/conf.d/99-wex.ini